"""
    TIMELINE ASSIGN
"""
TIMELINE_ASSIGN_NEG_T2_ID = 1  # T-2
TIMELINE_ASSIGN_NEG_T1_ID = 2  # T-1
TIMELINE_ASSIGN_T_ID = 3  # T
TIMELINE_ASSIGN_POS_T1_CUS_ID = 4  # T+1 Customer input
TIMELINE_ASSIGN_POS_T1_EMP_ID = 5  # T+1 Employee input

TIMELINES = {
    TIMELINE_ASSIGN_NEG_T2_ID: "T-2",
    TIMELINE_ASSIGN_NEG_T1_ID: "T-1",
    TIMELINE_ASSIGN_T_ID: "T",
    TIMELINE_ASSIGN_POS_T1_CUS_ID: "T+1_CUS",
    TIMELINE_ASSIGN_POS_T1_EMP_ID: "T+1_EMP"
}
