from loguru import logger
from database.models import *

async def repo_provinces(oracle_session):
    models = [
        AssetOther,
        AssetRealEstate,
        AssetTransportation,
        BusinessFinanceCashFlow,
        BusinessFinanceCashFlowVendor,
        BusinessFinanceCashFlowValue,
        CollateralCargo,
        CollateralMachine,
        CollateralOther,
        CollateralOwner,
        CollateralPaper,
        CollateralApartment,
        CollateralLandAsset,
        CollateralMarket,
        CollateralLand,
        CollateralRealEstate,
        CollateralRightProperty,
        CollateralStock,
        CollateralTransportation,
        Collateral,
        CreditCard,
        CreditCollateral,
        CreditInstitution,
        CreditInstitutionLoan,
        CytmCcyDefnMaster,
        FinanceMetadata,
        FinanceMetadataGroup,
        FinanceMetadataItem,
        FinanceTimeline,
        FinanceTimelineAssign,
        IncomeSequence,
        UdtmLov,
        # District,
        # Country,
        # Branch,
        # Province,
        # Ward,
        SourceIncomePension,
        SourceIncomeStock,
        SourceIncomeSalary,
        SourceIncomeOther,
        SourceIncomeGroupAsset,
        SourceIncomeDeposit,
        SourceIncomeCompany,
        SourceIncomeBusinessHousehold, Profile,
        ProfileRiskItem,
        ProfileIncome,
        ProfileExceptionItem,
        ProfileCost,
        Policy,
        PolicyRule,
        PolicyGroup,
        PolicyDetail,
        Person,
        PersonalRelationship,
        PersonMarried,
        PersonIdentity,
        PersonGroupIncome,
        PersonFccCore,
        PersonEducation,
        PersonCreditInstitutionRelationship,
        PersonBusiness,
        PersonBusinessFinanceReport,
        PersonBusinessAddress,
        PersonAddress,
        MaBusinessLine,
        MaFrequence,
        LoanProduct,
        LoanProductPolicy,
        DetmClgBrnCode,
        MaBankCode,
        GetmCollCategory,
        MaPersonalRep,
        MaCollType,
        MaBusinessType,
        MaCustomerType,
        Partner,
        PartnerProduct,
        PartnerLoanProduct,
        ProfileSequenceItem,
        ProfileScore,
        MaDocumentType,
        MaQuestion,
        ProductDocumentRule,
        ProductQuestion,
        ProfileAnswerCus,
        ProfileDocument,
        MaCreditGroupCustomer,
        ProfileCreditModified,
        ProfileCreditPublished,
        ProfileCreditSequenceItem,
        ProfileCreditSuppCard,
        MaCardPromotion,
        ProductPromotion,
        ProfileCreditCardDelivery,
        ProfileCreditPromotion,
        MaCreditGroupCustomerItem,
        PersonCreditScoreSegment,
        PersonCreditScore,
        MaCicScore,
        MaCicScoreDetail,
        RegionalOffice,
        ProfileCreditStatementMethod
    ]
    for model in models:
        try:
            data = oracle_session.query(model).all()  # noqa
        except Exception as ex:
            logger.error(model)
            logger.warning(ex)
            break
    provinces = oracle_session.query(Province.province_code, Province.description).all()
    return provinces
