from enum import Enum

# Các bước cic cấp 1
from app.utils.constant.legal_info_constants import (
    LEGAL_TYPE_BORROWER, LEGAL_TYPE_CO_BORROWER, LEGAL_TYPE_CO_PAYER,
    LEGAL_TYPE_LAW_RELATED, LEGAL_TYPE_MARRIAGE, LEGAL_TYPE_OTHER,
    LEGAL_TYPE_RELATED
)
from app.utils.functions import to_lower_dash

CIC_STEP_LV1_OTHER_CREDIT_INSTITUTION = 'QUAN_HE_TIN_DUNG_TAI_CAC_TO_CHUC_TIN_DUNG_KHAC'
CIC_STEP_LV1_CURRENT_CREDIT_INSTITUTION = 'KHOAN_VAY_HIEN_HUU_TAI_SCB'

CREDIT_SHORT_TERM_DURATION_MIN = 1
CREDIT_SHORT_TERM_DURATION_MAX = 12
CREDIT_MEDIUM_TERM_DURATION_MIN = 13
CREDIT_MEDIUM_TERM_DURATION_MAX = 60
CREDIT_LONG_TERM_DURATION_MIN = 61
CREDIT_LONG_TERM_DURATION_MAX = float('inf')
CREDIT_OTHER_DURATION_MIN = float("-inf")
CREDIT_OTHER_DURATION_MAX = float("inf")

# Nhóm nợ cao nhất
DEBT_CLASSIFICATION_NORM = 'NORM'  # N1 - NO DU TIEU CHUAN
DEBT_CLASSIFICATION_OD02 = 'OD02'  # N2 - NO CAN CHU Y
DEBT_CLASSIFICATION_OD04 = 'OD04'  # N4 - NO NGHI NGO
DEBT_CLASSIFICATION_OD05 = 'OD05'  # N5 - NO CO KHA NANG MAT VON
DEBT_CLASSIFICATION_OD03 = 'OD03'  # N3 - NO DUOI TIEU CHUAN
# Loai quan he
CHU_THE_CHINH = "CHU_THE_CHINH"
NGUOI_GIOI_THIEU = "NGUOI_GIOI_THIEU"
DOI_TUONG_KHAC = "DOI_TUONG_KHAC"
# Activated flag
YES = 'Y'
NO = 'N'

# Phương thức cấp tín dụng: Ngắn hạn, Trung hạn, Dài hạn
# TODO: Check db
PROPERTY_CREDIT_SHORT_TERM = 'SHORT'
PROPERTY_CREDIT_MEDIUM_TERM = 'MEDIUM'
PROPERTY_CREDIT_LONG_TERM = 'LONG'
PROPERTY_CREDIT_OTHER = 'OTHER'

# Khoản vay thẻ step 1 (card loan)
OTHER_INSTITUTION = "other_institution"
SCB_INSTITUTION = "scb_institution"
# Khoản vay thẻ step 2 (card loan)
CARD_HOLDER = "card_holder"
PRESENTER = "presenter"
OTHER_PERSON = "other_person"

# Thông tin tổ chức tín dụng SCB
ID_SCB = 106
CODE_SCB = '79334001'

# customer_type
BORROWER = 'borrower'
MARRIAGE = 'marriage'
CO_BORROWER = 'co_brw'
CO_PAYER = 'co_payer'
LAW_RLT = 'law_rlt'
RELATED = 'related'
OTHERS = 'others'


class EDebtClassification(str, Enum):
    DEBT_NORM = DEBT_CLASSIFICATION_NORM
    DEBT_OD02 = DEBT_CLASSIFICATION_OD02
    DEBT_0D04 = DEBT_CLASSIFICATION_OD04
    DEBT_0D03 = DEBT_CLASSIFICATION_OD03


RANK_SCORE_DEBT_CLASSIFICATION = {
    "NORM": 1,
    "OD02": 2,
    "OD03": 3,
    "OD04": 4,
    "OD05": 5
}

RANK_NAME_DEBT_CLASSIFICATION = {
    1: "NORM",
    2: "OD02",
    3: "OD03",
    4: "OD04",
    5: "OD05"
}


class ECICStepLv1(str, Enum):
    OTHER_CREDIT_INSTITUTION = CIC_STEP_LV1_OTHER_CREDIT_INSTITUTION
    CURRENT_CREDIT_INSTITUTION = CIC_STEP_LV1_CURRENT_CREDIT_INSTITUTION

    @staticmethod
    class DashVer(str, Enum):
        OTHER_CREDIT_INSTITUTION = to_lower_dash(CIC_STEP_LV1_OTHER_CREDIT_INSTITUTION)
        CURRENT_CREDIT_INSTITUTION = to_lower_dash(CIC_STEP_LV1_CURRENT_CREDIT_INSTITUTION)


class ECICStepLv1KVT(str, Enum):
    OTHER_INSTITUTION = OTHER_INSTITUTION
    SCB_INSTITUTION = SCB_INSTITUTION


# KVT(vay the)
class ECICStepLv2KVT(str, Enum):
    CARD_HOLDER = CARD_HOLDER
    PRESENTER = PRESENTER
    OTHER_PERSON = OTHER_PERSON
    # các bước cic cấp 2 của vay thẻ
    CHU_THE_CHINH = CHU_THE_CHINH
    NGUOI_GIOI_THIEU = NGUOI_GIOI_THIEU
    DOI_TUONG_KHAC = DOI_TUONG_KHAC


class ECICStepLv2(str, Enum):
    # Các bước cic cấp 2
    BORROWER = LEGAL_TYPE_BORROWER
    MARRIAGE = LEGAL_TYPE_MARRIAGE
    CO_BORROWER = LEGAL_TYPE_CO_BORROWER
    CO_PAYER = LEGAL_TYPE_CO_PAYER
    LAW_RELATED = LEGAL_TYPE_LAW_RELATED
    RELATED = LEGAL_TYPE_RELATED
    OTHER_PERSON = LEGAL_TYPE_OTHER

    @staticmethod
    class DashVer(str, Enum):
        BORROWER = to_lower_dash(LEGAL_TYPE_BORROWER)
        MARRIAGE = to_lower_dash(LEGAL_TYPE_MARRIAGE)
        CO_BORROWER = to_lower_dash(LEGAL_TYPE_CO_BORROWER)
        CO_PAYER = to_lower_dash(LEGAL_TYPE_CO_PAYER)
        LAW_RELATED = to_lower_dash(LEGAL_TYPE_LAW_RELATED)
        OTHER_PERSON = to_lower_dash(LEGAL_TYPE_OTHER)


class EActivatedFlag(str, Enum):
    YES = YES
    NO = NO


class EPropertyCredit(str, Enum):
    SHORT = PROPERTY_CREDIT_SHORT_TERM
    MEDIUM = PROPERTY_CREDIT_MEDIUM_TERM
    LONG = PROPERTY_CREDIT_LONG_TERM
    OTHER = PROPERTY_CREDIT_OTHER


# Loại document
DOCUMENT_TYPE_TTKV = 'TTKV'
DOCUMENT_TYPE_TTT = 'TTT'
DOCUMENT_TYPE_TTTSBD = 'TSBD'


class EDocumentTypeCic(str, Enum):
    TTKV = DOCUMENT_TYPE_TTKV
    TTT = DOCUMENT_TYPE_TTT
    TTTSBD = DOCUMENT_TYPE_TTTSBD


# khoản vay thẻ UDTM field name
CIC_CUS_SEGMENT = "CIC_CUS_SEGMENT"
CIC_SCORE_RANK_SCORE = "CIC_SCORE_RANK_SCORE"

# ID Tổ chức tín dụng hiện tại theo ORACLE DB (SCB)
CURRENT_CREDIT_INS_ID = 106
