from enum import Enum

# Loại quan hệ
LEGAL_TYPE_CREDIT_CARDHOLDER = "CREDIT_CARDHOLDER"  # "CHU_THE_CHINH"
LEGAL_TYPE_CREDIT_MARRIAGE = "CREDIT_MARRIAGE"  # "NGUOI_HON_PHOI"
LEGAL_TYPE_CREDIT_SUPP_CARD = "CREDIT_SUPP_CARD"  # "CHU_THE_PHU"
LEGAL_TYPE_CREDIT_RELATED = "CREDIT_RELATED"  # "NGUOI_LIEN_HE"
LEGAL_TYPE_CREDIT_REFERENCE = "CREDIT_REFERENCE"  # "NGUOI_GIOI_THIEU"
LEGAL_TYPE_CREDIT_OTHER = "CREDIT_OTHER"  # "DOI_TUONG_KHAC"

# loại người vay
CUSTOMER_TYPE_BORROWER = 'BORROWER'  # NGƯỜI VAY
CUSTOMER_TYPE_CO_BORROWER = "CO_BRW"  # NGƯỜI ĐỒNG VAY
CUSTOMER_TYPE_SPOUSE = "MARRIAGE"  # NGƯỜI HÔN PHỐI
CUSTOMER_TYPE_CO_PAYER = "CO_PAYER"  # NGƯỜI ĐỒNG TRẢ NỢ
CUSTOMER_TYPE_LAW_RLT = "LAW_RLT"  # ĐỐI LIÊN HỆ THEO QUY ĐỊNH PHÁP LUẬT
CUSTOMER_TYPE_RELATED = "RELATED"  # NGƯỜI LIÊN HỆ

# quốc tịch
COUNTRY = 'COUNTRY'
RELATED_MESSAGE = 'person related is require'


class ERelationshipType(str, Enum):
    """
        Loại quan hệ trong hồ sơ
        Table: LOS_MA_PERSONAL_REP
    """
    CREDIT_CARDHOLDER = LEGAL_TYPE_CREDIT_CARDHOLDER
    CREDIT_MARRIAGE = LEGAL_TYPE_CREDIT_MARRIAGE
    CREDIT_SUPP_CARD = LEGAL_TYPE_CREDIT_SUPP_CARD
    CREDIT_RELATED = LEGAL_TYPE_CREDIT_RELATED
    CREDIT_REFERENCE = LEGAL_TYPE_CREDIT_REFERENCE
    CREDIT_OTHER = LEGAL_TYPE_CREDIT_OTHER
