UDTM_MARITAL_STATUS = 'MARITAL_STATUS'

UDTM_ADDRESS_TYPE = 'ADDRESS_TYPE'

UDTM_ADDRESS_TYPE_CREDIT = 'ADDRESS_TYPE_CREDIT'

UDTM_OWNER_PROPERTY = 'OWNER_PROPERTY'

UDTM_RENTAL_OWNER_PROPERTY = 'RENTAL_OWNER_PROPERTY'

UDTM_EDUCATION = 'EDUCATION'

UDTM_CIF_ID_TYPE = 'CIF_ID_TYPE'

TYPE_CIF_ID_TYPE = 'CIF_ID_TYPE'  # CMND / CCCD / CIC

TYPE_ADDRESS_PERMANENT = 'PERMANENT'  # Địa chỉ thường chú

TYPE_ADDRESS_TEMP = 'TEMP'  # Địa chỉ tạm trú

TYPE_ADDRESS_WORK_LOCATION = 'WORK_LOCATION'  # Địa chỉ cơ quan

UDTM_RELATIONSHIP = 'RELATIONSHIP'

UDTM_REAL_ESTATE_STATUS = 'REAL_ESTATE_STATUS'

UDTM_DEBT_CLASSIFICATION = 'DEBT_CLASSIFICATION'

UDTM_CUSTOMER_TYPE = 'CUSTOMER_TYPE'

UDTM_CUSTOMER_TYPE_I = 'I'  # Loại khách hàng cá nhân

UDTM_SCHEDULE_UNIT = 'SCHEDULE_UNIT'

UDTM_LENDING_METHOD = 'LENDING_METHOD'

UDTM_REMARK = 'REMARK'

UDTM_BUSINESS_TYPE = 'BUSINESS_TYPE'

UDTM_CONTRACT_TERM = 'CONTRACT_TERM'

UDTM_DISBURSEMENT = 'DISBURSEMENT'

UDTM_SEX = 'SEX'

UDTM_BUSINESS_LICSENCE_TYPE = 'BUSINESS_LICENCE_TYPE'

UDTM_ACCEPT_FLAG = 'ACCEPT_FLAG'

UDTM_BUSINESS_TYPE_SH = 'BUSINESS_TYPE_SH'

UDTM_PAYMENT = 'PAYMENT'

UDTM_ACCEPT_CREDIT_LABEL = 'ACCEPT_CREDIT_LABEL'

UDTM_ABLE_PAY_LABEL = 'ABLE_PAY_LABEL'

UDTM_RISK_TYPE = 'RISK_TYPE'

UDTM_FATCA_INFO = 'CN_00_CUNG_CAP_TT_FATCA'

UDTM_AVERAGE_INCOME = 'THU_NHAP_BQ_03_THANG'

UDTM_CUST_CLASSIFICATION = 'CUST_CLASSIFICATION'

UDTM_RESIDENT_STATUS = 'RESIDENT_STATUS'

UDTM_LOAN_PURPOSE_CORE = 'MUC_DICH_VAY'

UDTM_ASSET_RENT_TYPE = "ASSET_RENT_TYPE"

UDTM_PRODUCT_CATEGORY = "PRODUCT_CATEGORY"

UDTM_FREQUENCE = 'FREQUENCE'

UDTM_MOVABLE_STATUS = "MOVABLE_STATUS"

UDTM_PRODUCT_LOAN_PURPOSE = 'LOAN_PURPOSE'

UDTM_OWNER_INPUT_TYPE = 'OWNER_INPUT_TYPE'

UDTM_CASH_FLOW_TYPE = 'CASHFLOW_TYPE'

UDTM_DOCUMENT_GROUP_TYPE = 'DOCUMENT_GROUP_TYPE'

MA_COLL_TYPE_REAL_ESTATE = "REST"

UDTM_COLLATERAL_OWNER_TYPE = 'COLLATERAL_OWNER_TYPE'

UDTM_COLLATERAL_SP_OWNER_TYPE = 'COLLATERAL_SP_OWNER_TYPE'

UDTM_LABEL_SOURCE_INCOME = 'LABEL_SOURCE'

UDTM_CAREER = 'MA_NGANH_NGHE'

UDTM_CREDIT_REF = 'CREDIT_REF'

UDTM_QUESTION = 'YN_QUESTION'

UDTM_DELIVERY_METHOD = 'CARD_DELIVERY_METHOD'

UDTM_PUBLICATION_SPEED_TYPE = 'PUBLICATION_SPEED_TYPE'

UDTM_CARD_DELIVERY_METHOD = 'CARD_DELIVERY_METHOD'

UDTM_CUSTOMER_NEED = 'CUSTOMER_NEED'

CIC_CUS_SEGMENT = 'CIC_CUS_SEGMENT'

MIN_VALUE = 0

MAX_VALUE = 10

MA_QUESTION = 'M1.01'

UDTM_CARD_PRODUCT_CATEGORY = 'PRODUCT_CATEGORY'

RESULT_ACCORDING_TO_CRITERIA = 'RESULT_ACCORDING_TO_CRITERIA'

UDTM_WORK_STATUS = 'WORK_SCHEDULE'

# khoản vay thẻ UDTM field name
CIC_SCORE_RANK_SCORE = "CIC_SCORE_RANK_SCORE"
# thời hạng cấp tín dụng
PRODUCT_CATEGORY_LIMIT = "PRODUCT_CATEGORY"

CIC_SCORE_RANK = 'CIC_SCORE_RANK'
UDTM_STATUS_CODE = 'STATUS_CODE'

UDTM_ACCEPT_STATUS = "ACCEPT_STATUS"

UDTM_BUSINESS_LICENCE_TYPE = 'BUSINESS_LICENCE_TYPE'

UDTM_USED_OTHER_CONTRACT_LABEL = "USED_OTHER_CONTRACT_LABEL"

UDTM_BUSINESS_REPRESENTATIVE = "HOUSEHOLD_BUSINESS_REPRESENTATIVE"

UDTM_CURRENT_CARD_GUARANTEE_FORM = "CURRENT_CARD_GUARANTEE_FORM"

# COLLATERAL

# Loai so huu, (tai san dam bao). Table: LOS_UDTM_LOV
COLLATERAL_OWNER_RELATIONSHIP_TYPE = "COLLATERAL_OWNER_TYPE"

# Đơn vị thực hiện thẩm định giá
VALUATION_UNIT_TYPE = "APPRAISAL_UNIT_TYPE_ID"

# Mục đích định giá
COLLATERAL_VALUATION_PURPOSE = "APPRAISAL_PURPOSE"

# Trạng thái bất động sản
COLLATERAL_REAL_ESTATE_STATUS = "REAL_ESTATE_STATUS"

# Loại vị trí
COLLATERAL_LOCATION_TYPE = "COLL_RE_POSITION_TYPE"

# Chiều rộng đường hiện hữu
COLLATERAL_LANE_WIDTH = "COLL_RE_ROAD_WIDTH"

# Loại GCN quyền sử dụng đất
COLLATERAL_LAND_CERT_TYPE = "COLL_RE_CERT_TYPE"

# Mục đích sử dụng đất (theo thẩm định giá) của đất của bất động sản loại 1
COLLATERAL_LAND_ASSET_VALUATION_LAND_USE_PURPOSE = "COLL_RE_LAND_USED_APPRI"

# Mục đích sử dụng đất (theo thẩm định giá) của đất của bất động sản loại 2
COLLATERAL_APARTMENT_VALUATION_LAND_USE_PURPOSE = "COLL_RE_APP_USED_APPRI"

# Nguồn gốc sử dụng đất theo GCN
COLLATERAL_CERT_LAND_USE_SOURCE = "COLL_RE_LAND_SOURCE"

# Hình thức sử dụng đất theo GCN
COLLATERAL_CERT_LAND_USE_FORM = "COLL_RE_LAND_USED_CERT"

# Pháp lý CTXD
COLLATERAL_LAND_ASSET_LEGAL = "COLL_RE_CONS_LEGAL"

# Loại GCN quyền sở hữu CTXD/nhà ở
COLLATERAL_CONST_CERT_TYPE = "COLL_RE_CONS_CERT_TYPE"

# Loại công trình
COLLATERAL_LAND_ASSET_TYPE = "COLL_RE_CONS_TYPE"

# Tình trạng pháp lý
COLLATERAL_APARTMENT_LEGAL_STATUS = "COLL_RE_APP_LEGAL_STATUS"

# Mục đích sử dụng đất (theo định giá)
COLLATERAL_APARTMENT_USED_PURPOSE = "COLL_RE_APP_USED_APPRI"

# Loại căn hộ
COLLATERAL_APARTMENT_TYPE = "COLL_RE_APP_ROOM_TYPE"

# Tình trạng PTVT
COLLATERAL_TRANS_STATUS = "COLL_TRANS_STATUS"

# Máy móc thiết bị / Tình trạng tài sản
COLLATERAL_MACHINE_STATUS = "COLL_MACHINE_STATUS"

# Vật tư hàng hóa / Tình trạng tài sản
COLLATERAL_CARGO_STATUS = "COLL_CARGO_STATUS"

# Quyền sở hữu tài sản / Tình trạng tài sản
COLLATERAL_RIGHT_PROPERTY_STATUS = "COLL_RIGHT_PROP_STATUS"

# Loại tài sản
COLLATERAL_BALANCE_TYPE = "COLL_PAPER_TYPE"
