from enum import Enum

PEOPLE_DEPEND_MIN = 0
PEOPLE_DEPEND_MAX = 10

CONFIG_KEY_ASSET_RENT_TYPE = "ASSET_RENT_TYPE"

NUM_SIGNATURE_MIN = 2
CREDIT_CUS_GROUP_ID = 27

YES = "Y"
NO = "N"
LOAN_TYPE_NORMAL = "LOAN"  # vay thường
LOAN_TYPE_CARD = "CREDIT"  # vay thẻ
DOCUMENT_PHAP_LY = 'PHAP_LY'
RELATIONSHIP_MARRIAGE = "COU"

# CARD_DELIVERY_METHOD
CARD_DELIVERY_METHOD_BRANCH = "BRANCH"
CARD_DELIVERY_METHOD_SCB_BRANCH_OTHER = "SCB_BRANCH_OTHER"
CARD_DELIVERY_METHOD_WORK_LOCATION = "WORK_LOCATION"
CARD_DELIVERY_METHOD_TEMP = "TEMP"
CARD_DELIVERY_METHOD_PERMANENT = "PERMANENT"
CARD_DELIVERY_METHOD_OTHER = "CARD_DELIVERY_METHOD"
BRANCH_ID = "0001"
CARD_DELIVERY_METHOD_AT_SCB = [CARD_DELIVERY_METHOD_BRANCH, CARD_DELIVERY_METHOD_SCB_BRANCH_OTHER]
CARD_DELIVERY_METHOD = [CARD_DELIVERY_METHOD_TEMP, CARD_DELIVERY_METHOD_PERMANENT, CARD_DELIVERY_METHOD_WORK_LOCATION]

# DOCUMENT TYPE OF 6 STEPS
DOCUMENT_PRODUCT_GROUP_ID = "NHOM_SAN_PHAM"
DOCUMENT_PRODUCT_GROUP_NAME = "NHÓM SẢN PHẨM"

DOCUMENT_LEGAL_INFO_ID = "THONG_TIN_PHAP_LY"
DOCUMENT_LEGAL_INFO_NAME = "THÔNG TIN PHÁP LÝ"

DOCUMENT_CIC_ID = "THONG_TIN_CIC"
DOCUMENT_CIC_NAME = "THÔNG TIN CIC"

DOCUMENT_LOAN_INFO_ID = "THONG_TIN_KHOAN_VAY"
DOCUMENT_LOAN_INFO_NAME = "THÔNG TIN KHOẢN VAY"

DOCUMENT_SOURCE_INCOME_ID = "NGUON_THU_NHAP"
DOCUMENT_SOURCE_INCOME_NAME = "NGUỒN THU NHẬP"

DOCUMENT_COLLATERAL_ID = "TAI_SAN_BAO_DAM"
DOCUMENT_COLLATERAL_NAME = "TÀI SẢN BẢO ĐẢM"

DOCUMENT_OTHER_PROFILE_ID = "HO_SO_KHAC"
DOCUMENT_OTHER_PROFILE_NAME = "HỒ SƠ KHÁC"

DOCUMENT_INTERNAL_CREDIT_RATING_ID = "XHTDNB"
DOCUMENT_INTERNAL_CREDIT_RATING_NAME = "XẾP HẠNG TÍN DỤNG NỘI BỘ"

SOURCE_INCOME_CUSTOMER_ID = "NGUON_THU_NHAP_CHU_THE_CHINH"
SOURCE_INCOME_CUSTOMER_NAME = "NGUỒN THU NHẬP CHỦ THẺ CHÍNH"

PRODUCT_LOAN_GROUP_LOAN = 'LOAN'
PRODUCT_LOAN_GROUP_CREDIT = 'CREDIT'


class EUdtmConfigFieldName(Enum):
    ASSET_RENT_TYPE = CONFIG_KEY_ASSET_RENT_TYPE


class ELoanTypeCode(str, Enum):
    NORMAL = LOAN_TYPE_NORMAL
    CARD = LOAN_TYPE_CARD


class EDocumentTypes(str, Enum):
    PRODUCT_GROUP_ID = DOCUMENT_PRODUCT_GROUP_ID
    PRODUCT_GROUP_NAME = DOCUMENT_PRODUCT_GROUP_NAME

    LEGAL_INFO_ID = DOCUMENT_LEGAL_INFO_ID
    LEGAL_INFO_NAME = DOCUMENT_LEGAL_INFO_NAME

    CIC_ID = DOCUMENT_CIC_ID
    CIC_NAME = DOCUMENT_CIC_NAME

    LOAN_INFO_ID = DOCUMENT_LOAN_INFO_ID
    LOAN_INFO_NAME = DOCUMENT_LOAN_INFO_NAME

    SOURCE_INCOME_ID = DOCUMENT_SOURCE_INCOME_ID
    SOURCE_INCOME_NAME = DOCUMENT_SOURCE_INCOME_NAME

    COLLATERAL_ID = DOCUMENT_COLLATERAL_ID
    COLLATERAL_NAME = DOCUMENT_COLLATERAL_NAME

    OTHER_PROFILE_ID = DOCUMENT_OTHER_PROFILE_ID
    OTHER_PROFILE_NAME = DOCUMENT_OTHER_PROFILE_NAME

    INTERNAL_CREDIT_RATING_ID = DOCUMENT_INTERNAL_CREDIT_RATING_ID
    INTERNAL_CREDIT_RATING_NAME = DOCUMENT_INTERNAL_CREDIT_RATING_NAME


class EYesNoQuestion(str, Enum):
    YES = YES
    NO = NO


YES_NO_SWITCHER = {
    True: EYesNoQuestion.YES,
    False: EYesNoQuestion.NO
}

BRANCH_ID = "000"  # HOI SO
